# Generated by Django 4.2.3 on 2024-04-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frutas',
            options={'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='verduras',
            options={'verbose_name_plural': 'Verduras'},
        ),
        migrations.RenameField(
            model_name='frutas',
            old_name='nome_da_fruta',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='frutas',
            old_name='preco_da_fruta',
            new_name='preco_do_produto',
        ),
        migrations.RenameField(
            model_name='frutas',
            old_name='quantidadeDisponivel',
            new_name='quantidade_disponivel',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='prcUnit',
            new_name='precoUnitario',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='mtPgto',
            new_name='metodo_de_pagemento',
        ),
        migrations.RenameField(
            model_name='verduras',
            old_name='nome_da_verdura',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='verduras',
            old_name='preco_da_vedura',
            new_name='preco_do_produto',
        ),
    ]
