# Generated by Django 4.2.3 on 2024-04-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_endereco_de_entrega_entrega_localentrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='entregaitem',
        ),
    ]
